apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-ai-backend
  labels:
    app: quantum-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quantum-ai
  template:
    metadata:
      labels:
        app: quantum-ai
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: quantum-ai
        image: quantum-ai-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            nvidia.com/gpu: 1
          limits:
            memory: "4Gi"
            cpu: "2000m"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: quantum-ai-service
spec:
  selector:
    app: quantum-ai
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
